on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 mingw-env:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            mingw-w64-x86_64-gcc
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      id: go
      with:
        go-version: 1.18
    - name: Build
      run: |

        go build -o "windows-amd64-latest" -v