on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64

        update: true
        install: |
            git
            make
            base-devel
            unzip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            
    - name: Grab Aubio
      run: |
        curl -o aubio.zip https://www.ledfx.app/downloads/aubio-0.5.0-alpha-win64.zip
        unzip aubio.zip
        mv aubio-0.5.0-alpha-win64/* C:/Users/RUNNER~1/AppData/Local/Temp/
        ls C:/Users/RUNNER~1/AppData/Local/Temp/
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         export CGO_CFLAGS='-IC:/Users/RUNNER~1/AppData/Local/Temp/include'
         export CGO_LDFLAGS='-LC:/Users/RUNNER~1/AppData/Local/Temp/lib' 
         export CGO_ENABLED=1
         go env
         go build -o 'windows-amd64-latest.exe' -v
    - name: Package LedFx
      run: |
         mkdir LedFx_${{ github.sha }}
         mv windows-amd64-latest.exe LedFx_${{ github.sha }}
         cp C:/Users/RUNNER~1/AppData/Local/Temp/bin/libaubio-5.dll LedFx_${{ github.sha }}/
         curl -o libportaudio.dll https://github.com/spatialaudio/portaudio-binaries/raw/master/libportaudio64bit.dll
         mv libportaudio.dll LedFx_${{ github.sha }}
    - name: Upload LedFx Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-amd64-latest.zip
        path: LedFx_${{ github.sha }}/