on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        # For speed + caching no need to update
        update: false
        install: |
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-cargo-c
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-waf
            mingw-w64-x86_64-ffmpeg
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get Aubio Files
      run: |
        git clone https://git.aubio.org/aubio/aubio aubio-src
        mv aubio-src/src '${{github.workspace}}\aubio'

    - name: Build LedFx
      run: |
        set CPLUS_INCLUDE_PATH='${{github.workspace}}\aubio'
        go build -o "windows-amd64-latest.exe" -v