on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-aubio
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         go build -o 'LedFx-windows-amd64-${{ github.sha }}.exe' -v
    - name: Package LedFx
      run: |
         export CYGPATH=$(cygpath -m /)
         mkdir LedFx_Builds/
         mv LedFx-windows-amd64-${{ github.sha }}.exe LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libaubio-5.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libportaudio.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avcodec-58.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avutil-56.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/avformat-58.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfftw3-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libfftw3f-3.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libwinpthread-1.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libsamplerate-0.dll LedFx_Builds/
    - name: Upload LedFx Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LedFx-windows-amd64-latest
        path: LedFx_Builds/
