on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |

        go build -o "windows-amd64-latest.exe" -v