on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64

        update: true
        install: |
            git
            make
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-waf
            
    - name: Build Aubio
      run: |
        git clone https://git.aubio.org/aubio/aubio
        cd aubio
        export CC=x86_64-w64-mingw32-gcc
        waf distclean configure build install --disable-samplerate --disable-jack --disable-flac --disable-sndfile --disable-avcodec --notests
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         export CGO_CFLAGS='-IC:/Users/RUNNER~1/AppData/Local/Temp/include'
         export CGO_LDFLAGS='-LC:/Users/RUNNER~1/AppData/Local/Temp/lib' 
         export CGO_ENABLED=1
         go env
         go build -o 'windows-amd64-latest.exe' -v