on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows Binaries


jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64

        update: true
        install: |
            git
            make
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
            
    - name: Grab Aubio
      run: |
        curl -o aubio.zip https://aubio.org/bin/0.4.6/aubio-0.4.6-win64.zip
        unzip aubio.zip
        ls
        mv aubio-0.4.6-win64/* C:/Users/RUNNER~1/AppData/Local/Temp/
        ls aubio-0.4.6-win64/
        ls C:/Users/RUNNER~1/AppData/Local/Temp/
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         export CGO_CFLAGS='-IC:/Users/RUNNER~1/AppData/Local/Temp/include'
         export CGO_LDFLAGS='-LC:/Users/RUNNER~1/AppData/Local/Temp/lib' 
         export CGO_ENABLED=1
         go env
         go build -o 'windows-amd64-latest.exe' -v